interface RozliczeniaDataGrid {
  id: number;
  orderNumber: string;
  date: string;
  employee: string;
  invoiceNumber: string;
  invoicePrice: string;
  dealer: string;
  dealerEmployee: string;
  status: string;
}

export const mockRozliczeniaData: RozliczeniaDataGrid[] = [
  {
    id: 1,
    orderNumber: "ff4-2023-90-KOs",
    date: "19/12/2022",
    employee: "Antonella Tidd",
    invoiceNumber: "fc/56/SM/30/pu",
    invoicePrice: "52864",
    dealer: "Sanford Inc Grupa Spółka Odpowiedzialność Pod Wezwaniem Ziutka",
    dealerEmployee: "Danit Robichon",
    status: "Accepted",
  },
  {
    id: 2,
    orderNumber: "663-2023-89-MAv",
    date: "27/02/2023",
    employee: "Chan McKeggie",
    invoiceNumber: "fc/42/BQ/55/sl",
    invoicePrice: "8066",
    dealer: "Homenick LLC",
    dealerEmployee: "Laverna Handford",
    status: "Accepted",
  },
  {
    id: 3,
    orderNumber: "0V3-2023-08-wvB",
    date: "07/05/2023",
    employee: "Wally Rameau",
    invoiceNumber: "fc/86/vI/44/tp",
    invoicePrice: "55",
    dealer: "O'Kon-Terry",
    dealerEmployee: "Atalanta Trunby",
    status: "Accepted",
  },
  {
    id: 4,
    orderNumber: "We6-2023-22-O3S",
    date: "01/08/2023",
    employee: "Murvyn Foort",
    invoiceNumber: "fc/39/Nk/75/tg",
    invoicePrice: "203",
    dealer: "Johnson LLC",
    dealerEmployee: "Wyatt Guitel",
    status: "Accepted",
  },
  {
    id: 5,
    orderNumber: "9J0-2023-13-RSo",
    date: "07/07/2023",
    employee: "Ravi Skillitt",
    invoiceNumber: "fc/02/Mo/00/wc",
    invoicePrice: "06",
    dealer: "Murray-Wunsch",
    dealerEmployee: "Brunhilda Cato",
    status: "Accepted",
  },
  {
    id: 6,
    orderNumber: "cV4-2023-56-yT8",
    date: "29/03/2023",
    employee: "Mariam Stuther",
    invoiceNumber: "fc/56/bO/06/hi",
    invoicePrice: "678",
    dealer: "Halvorson Group",
    dealerEmployee: "Amelie Clace",
    status: "Accepted",
  },
  {
    id: 7,
    orderNumber: "gh3-2023-24-GxZ",
    date: "19/08/2023",
    employee: "Hunter Cody",
    invoiceNumber: "fc/31/RZ/39/jb",
    invoicePrice: "418",
    dealer: "Schamberger-Cassin",
    dealerEmployee: "Yehudit Pauluzzi",
    status: "Accepted",
  },
  {
    id: 8,
    orderNumber: "7k5-2023-15-qjv",
    date: "14/05/2023",
    employee: "Chandler Menilove",
    invoiceNumber: "fc/19/FZ/56/zz",
    invoicePrice: "98",
    dealer: "Rippin Inc",
    dealerEmployee: "Suellen Franciottoi",
    status: "Accepted",
  },
  {
    id: 9,
    orderNumber: "Ed6-2023-13-YMT",
    date: "23/08/2023",
    employee: "Oliy Clyant",
    invoiceNumber: "fc/86/zy/32/dl",
    invoicePrice: "43",
    dealer: "D'Amore-Tromp",
    dealerEmployee: "Darcy Rotge",
    status: "Accepted",
  },
  {
    id: 10,
    orderNumber: "tm9-2023-71-8l0",
    date: "07/04/2023",
    employee: "Elana Groveham",
    invoiceNumber: "fc/96/ql/50/fg",
    invoicePrice: "735",
    dealer: "Robel-Krajcik",
    dealerEmployee: "Wells Lecount",
    status: "Accepted",
  },
  {
    id: 11,
    orderNumber: "ff4-2023-90-KOs",
    date: "19/12/2022",
    employee: "Antonella Tidd",
    invoiceNumber: "fc/56/SM/30/pu",
    invoicePrice: "52864",
    dealer: "Sanford Inc Grupa Spółka Odpowiedzialność Pod Wezwaniem Ziutka",
    dealerEmployee: "Danit Robichon",
    status: "Accepted",
  },
  {
    id: 12,
    orderNumber: "663-2023-89-MAv",
    date: "27/02/2023",
    employee: "Chan McKeggie",
    invoiceNumber: "fc/42/BQ/55/sl",
    invoicePrice: "8066",
    dealer: "Homenick LLC",
    dealerEmployee: "Laverna Handford",
    status: "Accepted",
  },
  {
    id: 13,
    orderNumber: "0V3-2023-08-wvB",
    date: "07/05/2023",
    employee: "Wally Rameau",
    invoiceNumber: "fc/86/vI/44/tp",
    invoicePrice: "55",
    dealer: "O'Kon-Terry",
    dealerEmployee: "Atalanta Trunby",
    status: "Accepted",
  },
  {
    id: 14,
    orderNumber: "We6-2023-22-O3S",
    date: "01/08/2023",
    employee: "Murvyn Foort",
    invoiceNumber: "fc/39/Nk/75/tg",
    invoicePrice: "203",
    dealer: "Johnson LLC",
    dealerEmployee: "Wyatt Guitel",
    status: "Accepted",
  },
  {
    id: 15,
    orderNumber: "9J0-2023-13-RSo",
    date: "07/07/2023",
    employee: "Ravi Skillitt",
    invoiceNumber: "fc/02/Mo/00/wc",
    invoicePrice: "06",
    dealer: "Murray-Wunsch",
    dealerEmployee: "Brunhilda Cato",
    status: "Accepted",
  },
  {
    id: 16,
    orderNumber: "cV4-2023-56-yT8",
    date: "29/03/2023",
    employee: "Mariam Stuther",
    invoiceNumber: "fc/56/bO/06/hi",
    invoicePrice: "678",
    dealer: "Halvorson Group",
    dealerEmployee: "Amelie Clace",
    status: "Accepted",
  },
  {
    id: 17,
    orderNumber: "gh3-2023-24-GxZ",
    date: "19/08/2023",
    employee: "Hunter Cody",
    invoiceNumber: "fc/31/RZ/39/jb",
    invoicePrice: "418",
    dealer: "Schamberger-Cassin",
    dealerEmployee: "Yehudit Pauluzzi",
    status: "Accepted",
  },
  {
    id: 18,
    orderNumber: "7k5-2023-15-qjv",
    date: "14/05/2023",
    employee: "Chandler Menilove",
    invoiceNumber: "fc/19/FZ/56/zz",
    invoicePrice: "98",
    dealer: "Rippin Inc",
    dealerEmployee: "Suellen Franciottoi",
    status: "Accepted",
  },
  {
    id: 19,
    orderNumber: "Ed6-2023-13-YMT",
    date: "23/08/2023",
    employee: "Oliy Clyant",
    invoiceNumber: "fc/86/zy/32/dl",
    invoicePrice: "43",
    dealer: "D'Amore-Tromp",
    dealerEmployee: "Darcy Rotge",
    status: "Accepted",
  },
  {
    id: 20,
    orderNumber: "tm9-2023-71-8l0",
    date: "07/04/2023",
    employee: "Elana Groveham",
    invoiceNumber: "fc/96/ql/50/fg",
    invoicePrice: "735",
    dealer: "Robel-Krajcik",
    dealerEmployee: "Wells Lecount",
    status: "Accepted",
  },
];
